### ISSUE TITLE
Look into version of Spark that is downloaded

### ISSUE THREAD

**Issue by vmk** [sara-nl/hathi-client#5]
In the current get scrip Spark for Hadoop 2.6 (and higher) is fetched. Perhaps the hadoop libraries are not needed as they typically are present.

**Comment by schot** [comment]
The Spark website calls this version _'Pre-build with user-provided Hadoop [can use with most Hadoop distributions]'_. I think this is the preferred version for us, but we should test to be sure.

**Comment by schot** [comment]
Seems to work after setting `SPARK_DIST_CLASSPATH` in `spark-env.sh` according to http://spark.apache.org/docs/latest/hadoop-provided.html.
